"""empty message

Revision ID: afe16c879727
Revises: fffa2c1ecc1e
Create Date: 2023-06-27 20:31:14.457991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afe16c879727'
down_revision = 'fffa2c1ecc1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=50), nullable=False))
        batch_op.create_unique_constraint(None, ['email'])
        batch_op.drop_column('hair_color')
        batch_op.drop_column('eye_color')
        batch_op.drop_column('height')
        batch_op.drop_column('mass')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mass', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('height', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('eye_color', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('hair_color', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
